version: "3.8"
services:
  scraper-api:
    image: ghcr.io/guillauterot/my-scraper:latest # tout en minuscules
    container_name: scraper-api
    restart: unless-stopped
    ports:
      - "3000:3000"
