name: Deploy scraper to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build project (optionnel si tu compiles TS -> JS)
        run: npm run build

      - name: "SSH deploy to Raspberry Pi"
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_PORT || 22 }}
          script: |
            set -e
            cd ~/my-scraper

            # reset dépôt à la dernière version
            git fetch --all
            git reset --hard origin/master

            # installer dépendances (le client Prisma est déjà généré)
            npm ci --production

            # redémarrer avec pm2
            if pm2 describe my-scraper-api > /dev/null; then
              pm2 restart my-scraper-api
            else
              pm2 start server.js --name my-scraper-api
            fi

            pm2 save
